# 单元刚度矩阵

三个节点坐标分别为 $x_0,y_0,x_1,y_1,x_2,y_2$ ，记作 $\mathbf{P}^e=[x_0,y_0,x_1,y_1,x_2,y_2]^T$ ；

三个节点位移分别为 $u_0,v_0,u_1,v_1,u_2,v_2$ ，记作 $\mathbf{A}^e=[u_0,v_0,u_1,v_1,u_2,v_2]^T$ 。

设单元任意点坐标为 $\mathbf{x}=[x,y]^T$ ，单元任意点位移为 $\mathbf{u}=[u,v]^T$ 。

二倍单元面积为
$$
\Delta=\begin{vmatrix}
1 & x_0 & y_0 \\
1 & x_1 & y_1 \\
1 & x_2 & y_2
\end{vmatrix}
$$
设型函数为
$$
S_0=\frac{1}{\Delta}
\begin{vmatrix}
1 & x   & y   \\
1 & x_1 & y_1 \\
1 & x_2 & y_2
\end{vmatrix}
\quad
S_1=\frac{1}{\Delta}
\begin{vmatrix}
1 & x   & y   \\
1 & x_2 & y_2 \\
1 & x_0 & y_0
\end{vmatrix}
\quad
S_2=\frac{1}{\Delta}
\begin{vmatrix}
1 & x   & y   \\
1 & x_0 & y_0 \\
1 & x_1 & y_1
\end{vmatrix}
$$
定义位置矩阵 $\mathbf{S}$
$$
\mathbf{S}=\begin{bmatrix}
S_0 &  0  & S_1 &  0  & S_2 &  0  \\
 0  & S_0 &  0  & S_1 &  0  & S_2
\end{bmatrix}
$$
因
$$
\mathbf{x}=\mathbf{S} \mathbf{P}^e
$$
单元中任意点的位移为
$$
\mathbf{u}=\mathbf{S} \mathbf{P}^e
$$

应变定义为
$$
\varepsilon=\frac{1}{2}\big[\nabla_\mathbf{x} \mathbf{u}+(\nabla_\mathbf{x} \mathbf{u})^T\big]
$$
由于应变只有三个独立分量，所以定义工程应变（向量）为
$$
\epsilon=\begin{bmatrix}
\varepsilon_{11}\\
\varepsilon_{22}\\
\varepsilon_{12}+\varepsilon_{21}
\end{bmatrix}
$$
所以工程应变和位移的关系为
$$
\epsilon=\begin{bmatrix}
\frac{\partial u}{\partial x}\\
\frac{\partial v}{\partial y}\\
\frac{\partial v}{\partial x}+\frac{\partial u}{\partial y}
\end{bmatrix}
$$
定义
$$
\mathbf{L}=\begin{bmatrix}
\frac{\partial}{\partial x} &              0              \\
             0              & \frac{\partial}{\partial y} \\
\frac{\partial}{\partial x} & \frac{\partial}{\partial y}
\end{bmatrix}
$$
则
$$
\epsilon=\begin{bmatrix}
\frac{\partial}{\partial x} &              0              \\
             0              & \frac{\partial}{\partial y} \\
\frac{\partial}{\partial x} & \frac{\partial}{\partial y}
\end{bmatrix}
\begin{bmatrix}
u\\
v
\end{bmatrix}
=\mathbf{L}\mathbf{u}
=\mathbf{L}(\mathbf{S}\mathbf{P}^e)
=(\mathbf{L}\mathbf{S})\mathbf{P}^e
$$
定义
$$
\mathbf{B}=\mathbf{L}\mathbf{S}
=\frac{1}{\Delta}
\begin{bmatrix}
y_1-y_2 &    0    & y_2-y_0 &    0    & y_0-y_1 &    0    \\
   0    & x_2-x_1 &    0    & x_0-x_2 &    0    & x_1-x_0 \\
x_2-x_1 & y_1-y_2 & x_0-x_2 & y_2-y_0 & x_1-x_0 & y_0-y_1  
\end{bmatrix}
$$
则
$$
\epsilon=\mathbf{B}\mathbf{A}^e
$$

线性本构方程定义为
$$
\sigma=\mathbf{D}\epsilon
$$

弹性变形能为
$$
\Psi=\frac{1}{2}\int_{\mathrm{element}}t\sigma^T\epsilon ds=\frac{1}{2}\int_{\mathrm{element}}t\mathbf{A}^{eT}\mathbf{B}^T\mathbf{D}\mathbf{B}\mathbf{A}^e ds=\frac{1}{2}\mathbf{A}^{eT} \left( \int_{\mathrm{element}}t\mathbf{B}^T\mathbf{D}\mathbf{B} ds \right) \mathbf{A}^e
$$
定义单元刚度矩阵
$$
\mathbf{K}^e=\int_{\mathrm{element}}t\mathbf{B}^T\mathbf{D}\mathbf{B}ds=t\Delta\mathbf{B}^T\mathbf{D}\mathbf{B}
$$
所以
$$
\Psi=\frac{1}{2}\mathbf{A}^{eT}\mathbf{K}^e\mathbf{A}^e
$$

根据虚功原理
$$
\delta\Psi-(\delta\mathbf{A}^e)^T\mathbf{F}^e=(\delta\mathbf{A}^e)^T\mathbf{K}^e\mathbf{A}^e-(\delta\mathbf{A}^e)^T\mathbf{F}^e
$$
由于 $\delta\mathbf{A}^e$ 的任意性，可以将其消去
$$
\mathbf{K}^e\mathbf{A}^e=\mathbf{F}^e
$$
即得到了单元的有限元方程。

In [1]:
import numpy as np

下面看一个单元刚度矩阵的例子，假设三角形单元的三个节点为

In [2]:
x0,y0=0.0,0.0
x1,y1=0.0,1.0
x2,y2=1.0,0.0

首先求出二倍面积

In [3]:
matrix=np.array([
    [1.0,x0,y0], 
    [1.0,x1,y1], 
    [1.0,x2,y2]])
det=np.linalg.det(matrix)
area_2=abs(det)
print('area_2 = %f'%area_2)

area_2 = 1.000000


接下来求出 B 矩阵

In [4]:
B=1/area_2*np.array([
    [y1-y2,0.0,y2-y0,0.0,y0-y1,0.0], 
    [0.0,x2-x1,0.0,x0-x2,0.0,x1-x0], 
    [x2-x1,y1-y2,x0-x2,y2-y0,x1-x0,y0-y1]])
B

array([[ 1.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  1.,  0., -1.,  0.,  0.],
       [ 1.,  1., -1.,  0.,  0., -1.]])

为了计算单元刚度矩阵，首先定义本构矩阵

In [5]:
E=10.0
nv=0.3
D=E/((1.0+nv)*(1.0-2*nv))*np.array([
    [1.0-nv,nv,0.0], 
    [nv,1.0-nv,0.0], 
    [0.0,0.0,0.5-nv]])
D

array([[13.46153846,  5.76923077,  0.        ],
       [ 5.76923077, 13.46153846,  0.        ],
       [ 0.        ,  0.        ,  3.84615385]])

In [6]:
K_element=area_2*B.T@D@B
K_element

array([[ 17.30769231,   9.61538462,  -3.84615385,  -5.76923077,
        -13.46153846,  -3.84615385],
       [  9.61538462,  17.30769231,  -3.84615385, -13.46153846,
         -5.76923077,  -3.84615385],
       [ -3.84615385,  -3.84615385,   3.84615385,   0.        ,
          0.        ,   3.84615385],
       [ -5.76923077, -13.46153846,   0.        ,  13.46153846,
          5.76923077,   0.        ],
       [-13.46153846,  -5.76923077,   0.        ,   5.76923077,
         13.46153846,   0.        ],
       [ -3.84615385,  -3.84615385,   3.84615385,   0.        ,
          0.        ,   3.84615385]])